// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TerAustralis.Api.Data;

#nullable disable

namespace TerAustralis.Api.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder b)
    {
#pragma warning disable 612, 618
        b.HasAnnotation("ProductVersion", "9.0.5")
         .HasAnnotation("Relational:MaxIdentifierLength", 63)
         .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

        b.Entity("Microsoft.AspNetCore.Identity.IdentityRole", e =>
        {
            e.Property<string>("Id").HasColumnType("text");
            e.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
            e.Property<string>("Name").HasMaxLength(256).HasColumnType("character varying(256)");
            e.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("character varying(256)");
            e.HasKey("Id");
            e.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
            e.ToTable("AspNetRoles");
        });

        b.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", e =>
        {
            e.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer")
             .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            e.Property<string>("ClaimType").HasColumnType("text");
            e.Property<string>("ClaimValue").HasColumnType("text");
            e.Property<string>("RoleId").IsRequired().HasColumnType("text");
            e.HasKey("Id");
            e.HasIndex("RoleId").HasDatabaseName("IX_AspNetRoleClaims_RoleId");
            e.ToTable("AspNetRoleClaims");
        });

        b.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", e =>
        {
            e.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer")
             .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            e.Property<string>("ClaimType").HasColumnType("text");
            e.Property<string>("ClaimValue").HasColumnType("text");
            e.Property<string>("UserId").IsRequired().HasColumnType("text");
            e.HasKey("Id");
            e.HasIndex("UserId").HasDatabaseName("IX_AspNetUserClaims_UserId");
            e.ToTable("AspNetUserClaims");
        });

        b.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", e =>
        {
            e.Property<string>("LoginProvider").HasColumnType("text");
            e.Property<string>("ProviderKey").HasColumnType("text");
            e.Property<string>("ProviderDisplayName").HasColumnType("text");
            e.Property<string>("UserId").IsRequired().HasColumnType("text");
            e.HasKey("LoginProvider", "ProviderKey");
            e.HasIndex("UserId").HasDatabaseName("IX_AspNetUserLogins_UserId");
            e.ToTable("AspNetUserLogins");
        });

        b.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", e =>
        {
            e.Property<string>("UserId").HasColumnType("text");
            e.Property<string>("RoleId").HasColumnType("text");
            e.HasKey("UserId", "RoleId");
            e.HasIndex("RoleId").HasDatabaseName("IX_AspNetUserRoles_RoleId");
            e.ToTable("AspNetUserRoles");
        });

        b.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", e =>
        {
            e.Property<string>("UserId").HasColumnType("text");
            e.Property<string>("LoginProvider").HasColumnType("text");
            e.Property<string>("Name").HasColumnType("text");
            e.Property<string>("Value").HasColumnType("text");
            e.HasKey("UserId", "LoginProvider", "Name");
            e.ToTable("AspNetUserTokens");
        });

        b.Entity("TerAustralis.Api.Models.ApplicationUser", e =>
        {
            e.Property<string>("Id").HasColumnType("text");
            e.Property<int>("AccessFailedCount").HasColumnType("integer");
            e.Property<string>("AvatarUrl").HasMaxLength(500).HasColumnType("character varying(500)");
            e.Property<string>("Bio").HasMaxLength(500).HasColumnType("character varying(500)");
            e.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
            e.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            e.Property<string>("DisplayName").HasMaxLength(100).HasColumnType("character varying(100)");
            e.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)");
            e.Property<bool>("EmailConfirmed").HasColumnType("boolean");
            e.Property<bool>("LockoutEnabled").HasColumnType("boolean");
            e.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
            e.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)");
            e.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)");
            e.Property<string>("PasswordHash").HasColumnType("text");
            e.Property<string>("PhoneNumber").HasColumnType("text");
            e.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean");
            e.Property<string>("RefreshToken").HasColumnType("text");
            e.Property<DateTime?>("RefreshTokenExpiry").HasColumnType("timestamp with time zone");
            e.Property<string>("SecurityStamp").HasColumnType("text");
            e.Property<bool>("TwoFactorEnabled").HasColumnType("boolean");
            e.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)");
            e.HasKey("Id");
            e.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
            e.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
            e.ToTable("AspNetUsers");
        });

        // FK relationships
        b.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", e =>
            e.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
             .WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired());

        b.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", e =>
            e.HasOne("TerAustralis.Api.Models.ApplicationUser", null)
             .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired());

        b.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", e =>
            e.HasOne("TerAustralis.Api.Models.ApplicationUser", null)
             .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired());

        b.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", e =>
        {
            e.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
             .WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            e.HasOne("TerAustralis.Api.Models.ApplicationUser", null)
             .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        b.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", e =>
            e.HasOne("TerAustralis.Api.Models.ApplicationUser", null)
             .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired());
#pragma warning restore 612, 618
    }
}
